Audio PR - Augmentation support [ Spectrogram ]
ROCm/MIVisionX pull request #1355
Opened 2024-05-20 15:59 UTC by fiona-gladwin

- Add Spectrogram augmentation support in MIVisionX
- Introduce layouts as NHW, NFT, NTF for audio cases

2024-05-20 17:00 UTC, LakshmiKumar23 approved these changes
@kiritigowda @rrawther This PR was already reviewed and merged before. Only adds the RPP_AUDIO flag. Looks good to merge if CI passes

2024-05-22 07:40 UTC, SundarRajan28 commented
@kiritigowda Synced PR branch with ToT

2024-05-28 00:36 UTC, rrawther requested changes
analyze to move many parameters into user_defined_struct

2024-05-28 22:49 UTC, rrawther approved these changes

2024-05-28 22:51 UTC, merged