OpenVX - GFX942: Fix canny test case (#1450)
ROCm/MIVisionX pull request #1457
Opened 2024-11-21 21:13 UTC by kiritigowda

* boundary check for canny

2024-11-21 21:55 UTC, hansely submitted a review, later dismissed

2024-11-22 16:43 UTC, LakshmiKumar23 approved these changes

2024-12-04 15:00 UTC, spolifroni-amd requested changes
Small changes in the changelog but they need to be done for the release notes script.

2024-12-04 15:00 UTC, spolifroni-amd commented on CHANGELOG.md
> +## (unreleased) MIVisionX 3.2.0
```suggestion
## (Unreleased) MIVisionX 3.2.0
```

2024-12-04 15:00 UTC, spolifroni-amd commented on CHANGELOG.md
>  ### Changes
```suggestion
### Changed
```

2024-12-04 15:36 UTC, kiritigowda commented
> Small changes in the changelog but they need to be done for the release notes script.

@spolifroni-amd changes accepted

2024-12-04 15:52 UTC, spolifroni-amd approved these changes

2024-12-04 20:08 UTC, hansely approved these changes

2024-12-06 22:02 UTC, LakshmiKumar23 approved these changes

2024-12-09 16:17 UTC, rrawther approved these changes

2024-12-09 17:07 UTC, merged